@startuml

 component "Source" as LIMS
 component "Consumer" as EPR
 component "Consumer" as HIE
 component "Consumer (ICS)" as ICS
 component "Intermediary" as TIE
 component "Clinical Data Repository\nHealth Information Exchange (HIE)" as CDR

 EPR -d[hidden]- ICS
 LIMS -r-> TIE : Send Event Notification\nHL7 v2 ORU_R01\nIHE LTW LAB-3
 TIE -r-> EPR: Send Event Notification\nHL7 v2 ORU_R01\nIHE LTW LAB-3\n(future FHIR Workflow - Task)
 TIE -r-> ICS: Send Event Notification\nHL7 v2 MDM_T021\nrelated to IHE DSUBm ITI-112
 TIE -d-> CDR: Populates
 HIE -u-> CDR: Query Genomic Data\nHL7 FHIR RESTful (read only)\nIHE QEDm PCC-44

@enduml

