@startuml

 component "Source" as LIMS
 component "Consumer" as EPR
 component "Data Consumer\n(Structured)" as HIE
 component "Document Consumer\n(Unstructured)" as HIEU
 component "Consumer (ICS)" as ICS
 component "Intermediary\nRegional Integration Engine (RIE)" as TIE
 component "Clinical Data Repository\nHealth Information Exchange (HIE)" as CDR

 EPR -d[hidden]- ICS
 LIMS -r-> TIE : **Send Genomic Report**\nHL7 v2 ORU_R01\nIHE LTW LAB-3
 TIE -r-> EPR: **Send Genomic Report**\nHL7 v2 ORU_R01\nIHE LTW LAB-3\n(future FHIR Workflow - Task)
 TIE -r-> ICS: **Send Document Message**\nHL7 v2 MDM_T02\nEvent notifications e.g. IHE DSUBm ITI-112 \nand MDM_T01 can be supported
 TIE -d-> CDR: **Populates**
 HIE -u-> CDR: **Query Genomic Data**\nHL7 FHIR RESTful (read only)\nIHE QEDm PCC-44
 HIEU -u-> CDR: **Query Genomic Report Documents**\nHL7 FHIR RESTful (read only)\nIHE MHD ITI-67 and ITI-68

@enduml

