@startuml

cloud HSCN [
HSCN
]

cloud internet [
Internet
]

node network <<router>> [
Genomics Regional Orchestration Engine - HSCN

----
DNS Name: gen-tie-test.nw-gmsa.nhs.uk????
DNS Name: gen-oauth2-test.nw-gmsa.nhs.uk????
Virtual IP: i.e. 10.x IP TODO?????
====
**Network Address Translation (NAT)**
Change external IP to
Virtual IP (for Alder Hey?)
]


node tie1 <<device>> [
Genomics RIE Mirror
====
Primary (Active)
----
Name: gen-tie-testt01.care.local
IP (Private): 100.64.48.171
SSL/TLS: gen-tie-test01.nw-gmsa.nhs.uk????
Port 443
]

node tie2 <<device>> [
Genomics RIE Mirror
====
Secondary
----
Name: gen-tie-test02.care.local
IP (Private): 100.64.48.172
SSL/TLS: gen-tie-test02.nw-gmsa.nhs.uk????
Port 443
]

node arbiter <<device>> [
Genomics RIE Arbiter
----
Monitors both RIE and controls
which RIE is primary (active)
]

node ig <<website>> [
Genomics Implementation Guide
----
DNS Name/SSL: fhir.nw-gmsa.nhs.uk
Acutal: https://nw-gmsa.github.io/R4
]

database database1 [
Database (Active)
]

database database2 [
Database Mirror
]

HSCN -- network
internet -- ig
network -d- tie1 : Mirror virtual IP address (VIP)
network -d- tie2

tie1 -r[hidden]- tie2
tie2 -r[hidden]- arbiter
arbiter -r[hidden]- ig
tie1 -- database1
database1 -r- database2: Online Backup
tie2 -- database2

@enduml
