@startmindmap


*  <b>Diagnostic Workflow</b>
** [[Questionnaire-GenomicTestOrder.html Laboratory Test Order (OML_O21)\nGenomic Test Order]]
*** [[StructureDefinition-ServiceRequest.html Service Request (ORC)]]
** [[Questionnaire-GenomicTestReport.html Laboratory Test Report (ORU_R01)\nGenomic Test Report]]
*** [[StructureDefinition-DiagnosticReport.html Diagnostic Report (OBR)]]
** Sample Management\nSpecimen Event Tracking
*** [[StructureDefinition-Specimen Specimen (SPM)]]
** [[StructureDefinition-Task.html Task (Future)]]
* Patient Administration
** [[StructureDefinition-Patient.html Patient (PID)]]
** [[StructureDefinition-HospitalSpell.html Encounter/Hospital Spell  (PV1)]]
** Care Directory
*** [[StructureDefinition-Organization.html Organisation]]
*** [[StructureDefinition-Practitioner.html Practitioner]]
* Health Documents
** [[StructureDefinition-DocumentReference.html Document Reference (OBX and XDS Document Entry)]]

@endmindmap
