  @startuml


  title "Federated Genomic Data Access and Genomic Archiving and Communication System (GACS)"

  hide footbox

  participant "Clinical Data Consumer" as DocumentConsumer

  participant "Health Information Exchange\nRegional Orchestration Engine (RIE)" as RIE

  participant "Clinical Data Source\nNW GMSA" as CDR1

  participant "Clinical Data Source\nNHS England GOMS" as CDR2

  DocumentConsumer -> RIE : FHIR REST API\nIHE Query Existing Data [QEDm)

== Federated Query Access Start ==

  RIE -> CDR1 : FHIR REST API\nIHE Query Existing Data [QEDm)
  CDR1 --> RIE: Response

  RIE -> CDR2 : FHIR REST API\nIHE Query Existing Data [QEDm)
  CDR2 --> RIE: Response

  RIE --> RIE: [[https://www.enterpriseintegrationpatterns.com/patterns/messaging/Aggregator.html Aggregate]] Responses
== Federated Query Access End ==

  RIE --> DocumentConsumer: Response

  @enduml
