@startuml

hide footbox

participant "Order Placer" as EPR
participant "Intermediary\nNW GLH Regional Orchestration Engine (RIE)" as TIE
participant "Order Filler" as LIMS

EPR -> EPR: Select Test Order Form
EPR -> EPR: Complete Test Order Form
EPR -> TIE: Submit Test Order Form\n(Send HL7 FHIR Message)\n**Laboratory Order O21**
TIE -> TIE: Validate Message

alt Successful validation
TIE --> EPR: Response HL7 FHIR Message\n**Positive acknowledgement (AA)**
TIE -> TIE : Transform HL7 FHIR to v2 Message
TIE -> LIMS: Send HL7 v2 Message\n**OML_O21/(ORM_O01)**
LIMS --> TIE: Response HL7 v2 Message\n**ORL_O22?**
else Unsuccessful validation
TIE --> EPR: Response HL7 FHIR Message\n**Application Reject (AR/AE)**
end

@enduml
