@startuml

frame "Regional Placer Order Management [LAB-1]" as LAB1 {
  component "**Order Filler**\n\nNW Genomic Laboratory Hub (LIMS)" as LIMS
  component "**Order Placer**\n\nRegional" as EPR
  component "**Intermediary**\n\nNW GLH Regional Orchestration Engine (RIE)" as TIE

 interface "HL7 FHIR Message\n**Laboratory Order O21**" as HL7_ORM1

 interface "HL7 v2.x\n**OML_O21/(ORM_O01)**" as HL7_ORM2


  EPR -d-> HL7_ORM1
  HL7_ORM1 -d-> TIE
  TIE -d-> HL7_ORM2
}



HL7_ORM2 -d-> LIMS



@enduml
