@startuml

title "Asynchronous Message Acknowledgement"

hide footbox

participant "Order Placer" as EPR
participant "Intermediary\nNW GLH Regional Orchestration Engine (RIE)" as TIE
participant "Order Filler" as LIMS

LIMS --> TIE: Response HL7 v2 Message\n**ORL_O22?**
TIE --> TIE: Store Message in a Message Queue
EPR -> TIE: Query for HL7 FHIR Messages
TIE --> EPR: Search results
EPR -> TIE: Update HL7 FHIR Messages
TIE --> EPR: Acknowledgement

@enduml
