@startuml


frame "Regional Order Results management [LAB-3]" as LAB3 {

component "**Order Filler**\n\nGenomic Laboratory Hub (GLH) LIMS" as LIMS

component "**Intermediary**\n\nNW GLH Regional Orchestration Engine (RIE)" as TIE

component "**Order Result Tracker**" as user

interface "HL7 v2 Message\nORU_R01" as HL7_ORU1

interface "HL7 v2 Message\nORU_R01" as HL7_ORU2

interface "HL7 FHIR Message\n**Laboratory Result R01**" as HL7_R01
}

LIMS -d-> HL7_ORU1
HL7_ORU1 -d-> TIE


TIE -d-> HL7_ORU2 : (un)structured\n(or structured report)
HL7_ORU2 -d-> user

TIE -d-> HL7_R01 : (un)structured\n(or composition [[https://build.fhir.org/ig/hl7-eu/laboratory/ HL7 EU Laboratory Report]])
HL7_R01 -d-> user

@enduml
