@startuml

title "Genomic Order Component Model - IHE LTW LAB-4"

frame "Regional Placer Order Management [LAB-1]" as LAB1 {
  component "**Order Filler**\n\nNW Genomic Laboratory Hub (LIMS)" as LIMS
  component "**Order Placer**\nRegional" as EPR
  component "**Intermediary**\nNorth West GLH Regional Orchestration Engine (RIE)" as TIE

 interface "HL7 FHIR Message\n**Laboratory Order O21**" as HL7_ORM1

 interface "HL7 v2.x\n**OML_O21/(ORM_O01)**" as HL7_ORM2

      EPR -d-> HL7_ORM1
  HL7_ORM1 -d-> TIE
  TIE -d-> HL7_ORM2
}

frame "National Work Order Management [LAB-4]" as LAB4 {
 component "**Order Placer**\nNational" as EPRE
 component "NHS England Genomic Order Management Service" as GOMSp
 component "**Order Filler**\n\nOther Regional Genomic Laboratory Hub (LIMS)" as LIMSE
 component "NHS England Genomic Order Management Service" as GOMS
 interface "Order Notification and Retrieval" as notify
 interface "HL7 FHIR Transaction\n(FHIR Workflow)" as Transaction


 EPRE -d-> GOMSp
 GOMSp -d-> notify
 notify -d[hidden]- Transaction
 GOMS -d-> LIMSE
}



TIE -d-> Transaction: Forwarded or Copy\nof Order
Transaction -d-> GOMS
 notify -d-> TIE

HL7_ORM2 -d-> LIMS



@enduml
