@startmindmap

title "Genomic Laboratory Order"

* Genomic Order
** Metadata
*** [[StructureDefinition-Patient.html Patient]]
**** Identification [[StructureDefinition-NHSNumber.html NHSNumber]] [[StructureDefinition-MedicalRecordNumber.html Medical Record Number]]
**** Name, date of birth, ethnic category, etc.
*** Case identification / Account Number [[StructureDefinition-HospitalProviderSpellIdentifier.html Hospital Provider Spell Identifier]]
** Laboratory Test Order
*** Test Details
**** [[StructureDefinition-PlacerOrderNumber.html Placer Order Number]]
**** [[StructureDefinition-FillerOrderNumber.html Filler Order Number]]
**** Ordering Facility [[StructureDefinition-OrganisationCode.html Organisation Code]]
**** Ordering Practitioner
**** Gene disease assessed [[CodeSystem-GenomicClinicalIndication.html Clinical Indication]]
**** Test Code [[CodeSystem-GenomicTestCode.html Test Directory Code]]
**** [[StructureDefinition-Specimen.html Specimen]]
***** Specimen Id
***** [[StructureDefinition-AccessionNumber.html Accession Number]]
***** [[StructureDefinition-ShipmentTrackingNumber.html Shipment Tracking number]]
*** Supporting Information\n(Ask At Order Entry Questions)
**** Consent
**** Pregnant
**** Consanguineous union

@endmindmap
