@startmindmap

title "Genomic Laboratory Report"

* [[StructureDefinition-DiagnosticReport.html Diagnostic Report]]
** Patient Administration
*** [[StructureDefinition-Patient.html Patient]]
**** Identification [[StructureDefinition-NHSNumber.html NHSNumber]]
**** Identification [[StructureDefinition-MedicalRecordNumber.html Medical Record Number]]
**** Name, date of birth, ethnic category, etc.
*** Case identification [[StructureDefinition-HospitalProviderSpellIdentifier.html Hospital Provider Spell Identifier]]
** Laboratory Report
*** [[Questionnaire-GenomicTestOrder.html Order Details]]
**** [[StructureDefinition-OrderIdentifier.html Placer Order Number]]
**** [[StructureDefinition-OrderFillerNumber.html Filler Order Number]]
**** Ordering Facility [[StructureDefinition-OrganisationCode.html Organisation Code]]
**** Gene disease assessed [[CodeSystem-GenomicClinicalIndication.html Clinical Indication]]
**** [[https://www.datadictionary.nhs.uk/data_elements/local_treatment_category_code.html Local Treatment Category Code]]
***** Genomic Test Code [[CodeSystem-GenomicTestCode.html Test Directory Code]]
**** [[StructureDefinition-Specimen.html Specimen]]
***** [[StructureDefinition-AccessionNumber.html Accession Number]]
*** Test Details
**** [[StructureDefinition-ReportNumber.html Report Number]]
**** Performer
**** Results Interpreter
**** Conclusion (Clinical Indication)
*** Results Genomic
**** Genomic Analysis Narrative Report (PDF) [[StructureDefinition-NWAttachment.html Attachment]]
**** Finding
***** [[#variant Variant]]
**** Implication
***** [[#diagnostic-implication Diagnostic Implication]]
***** [[#implications Therapeutic Implication]] ProgressRX
*** [[#genomic-study Genomic Study/Method]]
**** Gene disease assessed / Clinical Indication
**** Analysis method [Type]
**** NHS England Genomics Test Outcome
**** [[#genomic-study-analysis Genomic Study Analysis]]
***** Regions Studied / Gene mutations tested

@endmindmap
