@startmindmap

title "Genomic Laboratory Report"

* Laboratory Report
** Metadata
*** [[StructureDefinition-Patient.html Patient]]
**** Identification [[StructureDefinition-NHSNumber.html NHSNumber]] [[StructureDefinition-MedicalRecordNumber.html Medical Record Number]]
*** Case identification [[StructureDefinition-HospitalProviderSpellIdentifier.html Hospital Provider Spell Identifier]]
** Laboratory Test Result
*** Test Details
**** [[StructureDefinition-PlacerOrderNumber.html Placer Order Number]]
**** [[StructureDefinition-FillerOrderNumber.html Filler Order Number]]
**** Ordering Facility [[StructureDefinition-OrganisationCode.html Organisation Code]]
**** Gene disease assessed [[CodeSystem-GenomicClinicalIndication.html Clinical Indication]]
**** Test Code [[CodeSystem-GenomicTestCode.html Test Directory Code]]
**** [[StructureDefinition-ReportNumber.html Report Number]]
**** Performer
**** Results Interpreter
**** [[StructureDefinition-Specimen.html Specimen]]
***** [[StructureDefinition-AccessionNumber.html Accession Number]]
*** Genomic Results
**** Genomic Analysis Narrative Report (PDF) [[StructureDefinition-NWAttachment.html Attachment]]
**** See also [[https://ckm.openehr.org/ckm/archetypes/1013.1.3759/mindmap Genomic Variant Result (openEHR minmap)]]
**** See also [[https://ckm.openehr.org/ckm/archetypes/1013.1.4858/mindmap Simple Genetic Variant (openEHR minmap)]]
*** Genomic Study/Method
**** Gene disease assessed / Clinical Indication
**** Analysis method [Type]
**** NHS England Genomics Test Outcome
**** See also [[https://ckm.openehr.org/ckm/archetypes/1013.1.4256/mindmap Sequencing Assay (openEHR mindmap)]]

@endmindmap
