@startmindmap

title "Genomic Laboratory Report"

* [[StructureDefinition-DiagnosticReport.html Diagnostic Report]]
** Patient Administration
*** [[StructureDefinition-Patient.html Patient]]
**** Identification [[StructureDefinition-NHSNumber.html NHSNumber]]
**** Identification [[StructureDefinition-MedicalRecordNumber.html Medical Record Number]]
**** Name, date of birth, ethnic category, etc.
*** Case identification [[StructureDefinition-HospitalProviderSpellIdentifier.html Hospital Provider Spell Identifier]]
** Laboratory Report
*** [[Questionnaire-GenomicTestOrder.html Order Details]]
**** [[StructureDefinition-PlacerOrderNumber.html Placer Order Number]]
**** [[StructureDefinition-FillerOrderNumber.html Filler Order Number]]
**** Ordering Facility [[StructureDefinition-OrganisationCode.html Organisation Code]]
**** Gene disease assessed [[CodeSystem-GenomicClinicalIndication.html Clinical Indication]]
**** [[https://www.datadictionary.nhs.uk/data_elements/local_treatment_category_code.html Local Treatment Category Code]]
***** Genomic Test Code [[CodeSystem-GenomicTestCode.html Test Directory Code]]
**** [[StructureDefinition-Specimen.html Specimen]]
***** [[StructureDefinition-AccessionNumber.html Accession Number]]
*** Test Details
**** [[StructureDefinition-ReportNumber.html Report Number]]
**** Performer
**** Results Interpreter
**** Conclusion (Clinical Indication)
*** Results Genomic
**** Genomic Analysis Narrative Report (PDF) [[StructureDefinition-NWAttachment.html Attachment]]
**** Finding
***** [[StructureDefinition-Observation-Variant.html Variant]]
****** See also [[https://ckm.openehr.org/ckm/archetypes/1013.1.3759/mindmap openEHR Genomic Variant Result]]
****** See also [[https://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-variant.html HL7 Genomic Reporting Variant]]
**** Implication
***** [[StructureDefinition-Observation-DiagnosticImplication.html Diagnostic Implication]]
****** See also [[https://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-diagnostic-implication.html HL7 Genomic Reporting Diagnostic Implication]]
**** [[StructureDefinition-Observation-TherapeuticImplication.html Therapeutic Implication]] ProgressRX
***** See also [[https://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-therapeutic-implication.html HL7 Genomic Reporting Therapeutic Implication]]
*** [[StructureDefinition-Procedure-GenomicStudy.html Genomic Study/Method]]
**** Gene disease assessed / Clinical Indication
**** Analysis method [Type]
**** NHS England Genomics Test Outcome
**** See also [[https://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-genomic-study.html HL7 Genomic Reporting Genomic Study]]
**** [[https://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-genomic-study-analysis.html Genomic Study Analysis]]
***** Regions Studied / Gene mutations tested

@endmindmap
