@startuml

skinparam svgDimensionStyle false

hide footbox

title "Traditional Messaging plus Enterprise Clinical Data Repository"

participant "Order Placer" as EPR
participant "Intermediary\nRegional Orchestration Engine (RIE)" as TIE
participant "Enterprise\nClinical Data Repository" as CDR
participant "Order Filler" as LIMS


EPR -> EPR: Complete Order Form
EPR -> TIE: [[LAB-1.html Placer Order Managment (LAB-1)]] [[Questionnaire-GenomicTestOrder.html Genomic Order O21]] Command Message
TIE -> CDR: [[LAB-1.html Placer Order Managment (LAB-1)]] [[Questionnaire-GenomicTestOrder.html Genomic Order O21]] Document Message
alt accepted
TIE -> LIMS: [[LAB-1.html Placer Order Managment (LAB-1)]] [[Questionnaire-GenomicTestOrder.html Genomic Order O21]] Command Message

TIE -> CDR: [[StructureDefinition-Task.html FHIR Task]] (accepted) Event Message

LIMS -> LIMS: Perform Test

opt preliminary/paritial reports
LIMS -> LIMS: Create preliminary/partial report
LIMS -> TIE: [[LAB-3.html Order Results Management (LAB-3)]] [[StructureDefinition-Composition-GenomicReport.html Genomic Report R01]] Document Message
TIE -> CDR: [[LAB-3.html Order Results Management (LAB-3)]] [[StructureDefinition-Composition-GenomicReport.html Genomic Report R01]] Document Message
TIE -> CDR: [[StructureDefinition-Task.html FHIR Task]] (in-progress) Event Message
TIE -> EPR: [[LAB-3.html Order Results Management (LAB-3)]] [[StructureDefinition-Composition-GenomicReport.html Genomic Report R01]] Document Message

end

LIMS -> LIMS: Create final report
LIMS -> TIE: [[LAB-3.html Order Results Management (LAB-3)]] [[StructureDefinition-Composition-GenomicReport.html Genomic Report R01]] Document Message
TIE -> CDR: [[LAB-3.html Order Results Management (LAB-3)]] [[StructureDefinition-Composition-GenomicReport.html Genomic Report R01]] Document Message
TIE -> CDR: [[StructureDefinition-Task.html FHIR Task]] (completed) Event Message

TIE -> EPR: [[LAB-3.html Order Results Management (LAB-3)]] [[StructureDefinition-Composition-GenomicReport.html Genomic Report R01]] Document Message
else rejected
TIE -> EPR: General laboratory order response message O22
TIE -> CDR: [[StructureDefinition-Task.html FHIR Task]] (rejected) Event Message
end
@enduml
