@startuml

hide footbox

title "Communication Task, Subscription and Event Notifications"

participant "Practitioner" as practitioner
participant "Regional Orchestration Engine" as RIE


opt FHIR Subscription
practitioner -> RIE: Subscription to Order, Report or other
else Communication Request
practitioner -> RIE: CommunicationRequest Task
RIE -> RIE: Convert to a Subscription
end

opt when event occurs
RIE -> practitioner: Event Notification
end


@enduml
