@startuml

hide footbox

participant "Order Placer" as EPR
participant "Intermediary\nNW GLH Regional Orchestration Engine (RIE)" as TIE
participant "Order Filler" as LIMS

EPR -> EPR: Select Test Order Form
EPR -> EPR: Complete Test Order Form

== Submit Test Order Form IHE LAB-1 ==
EPR -> TIE: \nSend HL7 FHIR Message\n**Laboratory Order O21**
TIE -> LIMS: Send HL7 v2 Message\n**OML_O21**


== Collect Sample ==
EPR -> EPR: Collect Sample
LIMS -> LIMS: Update Test Order

@enduml
