@startuml

title "Genomic Archetype Overview"


class "[[Questionnaire-GenomicTestOrder.html Genomic Test Order]]" as Order <<aggregate>> {

}

class "[[Questionnaire-GenomicTestReport.html Genomic Test Report]]" as Report <<aggregate>>


Order o-r- "0..*" Report

@enduml
