@startuml

hide footbox

participant "Order Placer" as EPR
participant "Intermediary\nNW GLH Regional Orchestration Engine (RIE)" as TIE
participant "Order Filler" as LIMS

LIMS -> LIMS: Perform Diagnostic Test
LIMS -> LIMS: Write Preliminary Report

opt
== Send (Preliminary) Genomic Test Report IHE LAB-3 ==
LIMS -> TIE: Send HL7 v2 Message\n**Laboratory Report ORU_R01**
TIE -> EPR: Send HL7 v2 Message\n**Laboratory Report ORU_R01**
end
LIMS -> LIMS: Complete Report

== Send (final) Genomic Test Report IHE LAB-3 ==
LIMS -> TIE: Send HL7 v2 Message\n**Laboratory Report ORU_R01**
TIE -> EPR: Send HL7 v2 Message\n**Laboratory Report ORU_R01**

note over EPR, TIE
When all tests in the order are complete
end note
TIE -> EPR: Task complete notification\n(Can be an email notification)

@enduml
