  @startuml

  skinparam svgDimensionStyle false


    frame "Laboratory Order O21" as Composition {
      entity "[[StructureDefinition-Patient.html Patient]]" as PID {
      [[StructureDefinition-NHSIdentifier.html NHSIdentifier]]
      [[StructureDefinition-MedicalRecordNumber.html MedicalRecordNumber]]
      }




      entity "[[StructureDefinition-ServiceRequest.html ServiceRequest]] \n([[https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Design/Clinicalheadings#Test-Request Test Request]])" as ORC <<aggregate>> {
      orderPlacerNumber
      orderFillerNumber
      orderPlacerGroupNumber
      accessionNumber
      subject : Patient
      }

      entity "[[StructureDefinition-Specimen.html Specimen]] \n([[https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Design/Clinicalheadings#Primary-Sample Primary Sample]])" as SPM {
      identifier
      accessionNumber
      subject : Patient
      }

      class "ConditionCode" as DG1

      class "[[StructureDefinition-PractitionerRole.html PractitionerRole]]" as STF {
       organisation : ODSCode
       practitioner: GMP/GMC Number
       specialty: ClinicalSpecialty
      }

      class "ServieRequest.identifier \nOriginal Order" as previous {

      }


      frame "Supporting Information" as supportingInfo {



        class "[[StructureDefinition-Observation.html Observation]]" as OBX1 {
        value[x]
        code
        subject : Patient
        }


        class "[[StructureDefinition-Observation-Panel.html Observation Panel]]" as panel {
        hasmember
        code
        subject : Patient
        }

        entity "[[StructureDefinition-DocumentReference.html DocumentReference]]\nPreviousReports\nGenomicFamilyStructure" as documentReference <<aggregate>> {
           type
           subject : Patient
           context.encounter : [[StructureDefinition-HospitalProviderSpellIdentifier.html Visit Number]]
        }

        class "[[StructureDefinition-NWAttachment.html Attachment]]" as attachment {
         contentType
          url
        }

        class "[[StructureDefinition-Binary.html Binary]]" as binary

      }

      class "[[StructureDefinition-HospitalProviderSpellIdentifier.html Episode Number]]" as PV1

      documentReference *-d-> attachment

      attachment *-- binary : url

      panel *-d- "0" OBX1: hasmember

      OBX1 -d[hidden]- documentReference

   }

  frame "Patient Administration" {

   entity "[[StructureDefinition-Encounter.html Encounter]]" as encounter {
      identifier : [[StructureDefinition-HospitalProviderSpellIdentifier.html Episode Number]]
      encounter
      episode
      subject : Patient
      }

      entity "[[StructureDefinition-Patient.html Patient]]" as patient {
       [[StructureDefinition-NHSIdentifier.html NHSIdentifier]]
        [[StructureDefinition-MedicalRecordNumber.html MedicalRecordNumber]]
        name
        address
        birthDate
        gender
        telecom
      }


  }

  frame "Care Directory Services" {

    entity "[[StructureDefinition-Practitioner.html Practitioner]]" as practitioner {
    professionalCode
    name
    telecom
    }

    entity "[[StructureDefinition-Organization.html Organization]]" as organisation {
     odsCode
     name
     telecom
    }

  }



  ORC *-- "0" SPM : specimen /\n accessionNumber
  ORC o-- "1" PID : subject
  ORC o-- "0" PV1 : encounter
  ORC *-- "0" DG1 : reason\n(Reference/Code)
  ORC o-- "0" previous: basedOn
  ORC *-- "0" OBX1: supportingInfo
  ORC *-- "0" panel: supportingInfo
  ORC *-- "0" documentReference: supportingInfo
  ORC *-- "1" STF: requester
  SPM o-- "0" practitioner: collection.collector
  PV1 o-- "0" practitioner: participant.individual
  PV1 o-- "1" PID : subject
  SPM o-- "1" PID : subject
  documentReference o-- "1" PID : subject
  OBX1 o-- "1" PID : subject

  documentReference o-- "1" PV1 : context.encounter

  OBX1 o-- "1" PV1 : encounter

  PV1 -- encounter
  PID -- patient
  STF -- practitioner
  STF -- organisation


  @enduml
