@startuml

title "Genomic Report Component Model"

component "Genomic Laboratory Hub (GLH or LIMS)" as LIMS
component "External Genomic Laboratory Hubs (GLH or LIMS)\n(via NHS England Genomic Order Management Service)" as xLIMS

component "Electronic Patient\nRecord (EPR)" as EPR

component "Electronic Document\nManagement Systems (EDMS)" as EDMS

component "**Intermediary**\nNW GLH Regional Orchestration Engine (RIE)" as TIE
component "NHS England Genomic Order Management Service" as GOMS

frame "Document/Report Event Notification (to RIE)" as xNofify1 {
 interface "Multicast Notification Service" as MNS
}
frame "Document/Report Event Notification (from XDS)" as xNofify2 {
interface "IHE DSUBm" as DSUBm
}

frame "Document/Report Message Exchange (from RIE)" as xChange1 {
 interface "HL7 v2.x ORU\n(or FHIR Message)" as HL7_ORU1
}

frame "Document/Report Message Exchange (from RIE)" as xChange2 {

 interface "HL7 v2.x ORU\n(or FHIR Message)" as HL7_ORU2
 interface "IHE XDS ITI-41/MHD ITI-105\n(pdf or FHIR Document)" as MHD105
 interface "FHIR Transaction\n(FHIR Workflow)" as Transaction
}


frame "Document/Report Sharing" as xShare {
  interface "HL7 IPA\n(FHIR RESTful)" as IPA
  interface "IHE XDS ITI-18 & 43\nor MHD ITI-67 & 68\n(pdf or FHIR Document)" as MHD67
  interface "HL7 IPA\n(FHIR RESTful)" as IPA2
}




component "User Application" as user

LIMS -d-> HL7_ORU1
HL7_ORU1 -d-> TIE

xLIMS -d-> MNS
MNS -d-> TIE

TIE -d-> HL7_ORU2 : Option EPR
HL7_ORU2 -d-> EPR

TIE -d-> MHD105 : Option EDMS
MHD105 -d-> EDMS

TIE -d-> Transaction : **Electronic Forwarding**\nExternal EPR/EDMS\n(from internal LIMS only)
Transaction -d-> GOMS
GOMS -d-> IPA2

EDMS -d-> MHD67
EPR -d-> IPA

IPA -d-> user
MHD67 -d-> user
IPA2 -d-> user

EDMS --> DSUBm : Optional Document Notifications
DSUBm --> EPR

note right of TIE
Transforms between different formats
Can provide code conversions
Routes report
end note

@enduml
