@startuml

skinparam svgDimensionStyle false


  frame "Laboratory Report R01" as Composition {


    entity "[[StructureDefinition-DiagnosticReport.html DiagnosticReport]]" as OBR <<aggregate>> {
         identifier
         category
         code
         performer
         resultInterpreter
         basedOn: ServiceRequest.identifier
         results
         }


    entity "[[StructureDefinition-Patient.html Patient]]\n([[https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Design/Clinicalheadings#Patient Patient]] or [[https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Design/Clinicalheadings#Fetus Fetus]])" as PID {
    [[StructureDefinition-NHSIdentifier.html NHS Identifier]]
    [[StructureDefinition-MedicalRecordNumber.html MedicalRecordNumber]]
    }

    class "[[StructureDefinition-HospitalProviderSpellIdentifier.html Episode Number]]\nFrom the order" as PV1 {
    }

    class "[[StructureDefinition-ServiceRequest.html ServiceRequest]].identifier \n([[https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Design/Clinicalheadings#Test-Request Test Request]])" as ORC {
      accessionNumber or
      orderFillerNumber
    }

    class "[[StructureDefinition-Specimen.html Specimen]].identifier \n([[https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Design/Clinicalheadings#Primary-Sample Primary Sample]])" as SPM {
    identifier
    accessionNumber
    }

    frame Results {

         class "[[StructureDefinition-Observation.html Observation]]" as OBX {
           subject
           code
           value[x]
            }


            class "[[StructureDefinition-Observation-Panel.html Observation Panel]]" as panel {
            subject
            code
            hasmember
            }

         entity "[[StructureDefinition-DocumentReference.html DocumentReference]]\nGenomicFamilyStructure" as documentReference {
                 type
                 subject : Patient
                 context.encounter : [[StructureDefinition-HospitalProviderSpellIdentifier.html Episode Number]]
                content.attachment
              }


          class "[[StructureDefinition-NWAttachment.html Attachment]]" as OBX2 {
          contentType
          url
          }

          class "[[StructureDefinition-Binary.html Binary]]" as binary
    }
    class "[[StructureDefinition-PractitionerRole.html PractitionerRole]]" as STF {
       organisation : ODSCode
       practitioner: GMP/GMC Number
       specialty: ClinicalSpecialty
      }



     panel *-d- "0" OBX: hasmember
  }

  frame "Patient Administration" {

   entity "[[StructureDefinition-Encounter.html Encounter]]" as encounter {
      identifier : [[StructureDefinition-HospitalProviderSpellIdentifier.html Episode Number]]
      encounter
      episode
      subject : Patient
      }

      entity "[[StructureDefinition-Patient.html Patient]]" as patient {
       [[StructureDefinition-NHSIdentifier.html NHSIdentifier]]
        [[StructureDefinition-MedicalRecordNumber.html MedicalRecordNumber]]
        name
        address
        birthDate
        gender
        telecom
      }


  }

  frame "Care Directory Services" {

    entity "[[StructureDefinition-Practitioner.html Practitioner]]" as practitioner {
    professionalCode
    name
    telecom
    }

    entity "[[StructureDefinition-Organization.html Organization]]" as organisation {
     odsCode
     name
     telecom
    }

  }


OBR o-- practitioner: resultInterpreter
OBR o-- organisation: performer

OBR o-- "0" SPM
OBR "*" o--  ORC : basedOn.identifier
OBR o-- "1" PID : subject
OBR *-- "0" PV1 : encounter
OBR *-- "*" OBX : results
OBR *-- "0" panel: results
OBR *-- "*" OBX2: presentedForm



  ORC *-- "1" STF: requester
  SPM o-- "0" practitioner: collection.collector
  PV1 o-- "0" practitioner: participant.individual

OBX o-- PID: subject
panel o-- PID: subject
documentReference o-- PID: subject
documentReference *-- OBX2: content.attachment
documentReference o-- PV1: context.encounter
OBX2 *-- binary : url

 PV1 -- encounter
  PID -- patient
  STF -- practitioner
  STF -- organisation

@enduml
