@startuml


  agent "**Order Placer**\n\ne.g. EPR, Pathology LIMS" as Placer
  agent "**Order Filler**\n\nNW GLH LIMS" as Filler

  agent "**Order Result Tracker**\n\ne.g. EPR" as Tracker
  agent "**Intermediary**\n\nNW GLH Regional Orchestration Engine" as RIE

  frame "Out of Area Communication (Future)" as future {
    agent "**Intermediary**\n\nNHS England Gemonic\nOrder Management Service" as GOMS
    agent "**Order Placer**\n\ne.g. EPR, Pathology LIMS" as xPlacer
    agent "**Order Filler**\n\nExternal GLH LIMS" as xFiller
     agent "**Order Result Tracker**\n\ne.g. EPR" as xTracker
  }

Placer -r-> RIE: Orders
xPlacer -r-> GOMS: Orders
RIE <-r-> Filler: Orders and\nReports
RIE -u-> Tracker: Reports
GOMS -d-> xTracker: Reports
RIE <-d-> GOMS
GOMS <-r-> xFiller: Orders and\nReports

@enduml
