@startuml
title "NHS Trust Report Routing (ORU_R01)"

start

if (Ordering Facility in Region Distribution List) then (yes)
  :Ordering Facility Queue;
else (no)
  if (Has Ordering Facility) then (yes)
    :Get ICS from OrganisationAffiliation from NHS England \nOrganisation Terminolology Data FHIR API;
    switch (ICS)
      case (North West Region\n(QOP, QE1 and QYG))
        :Dead Letter Queue;
      case (Welsh)
        :DHCW Queue;
      case (Other Region in England)
        :NHS England GOMS Queue;
    endswitch
  else (no)
    :Dead Letter Queue;
  endif
endif


stop

@enduml
