# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: fhir.nwgenomics.nhs.uk
canonical: https://fhir.nwgenomics.nhs.uk
version: 0.2.1
name: NWGMSA
title: NHS North West Genomics
description: NHS North West Genomic Medicine Service Alliance - IHE Laboratory Testing Workflow (LTW)
releaseLabel: ci-build

status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: NHS North West Genomics
  - url: https://www.nwgenomics.nhs.uk/contact-us

license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: urn:iso:std:iso:3166#GB "United Kingdom of Great Britain and Northern Ireland"

#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2024+

dependencies:
  hl7.fhir.eu.base: 2.0.0-ballot
  fhir.r4.ukcore.stu3.currentbuild:
    version: 0.0.19-pre-release
    uri: https://simplifier.net/guide/ukcoreversionhistory
  hl7.fhir.uv.genomics-reporting: 3.0.0
  hl7.fhir.eu.laboratory: 0.1.1
  hl7.fhir.uv.sdc: 3.0.0
  hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.uv.xver-r5.r4: 0.0.1-snapshot-2
  ihe.iti.balp: 1.1.4

FSHOnly: false
# see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
parameters:
  path-binary: input/attachments
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  excludexml: 'false'
  excludettl: 'true'
  excludemap: 'true'
  generate:
    - xml
    - json
  path-expansion-params: '../resources/Parameters-exp-params.json'


#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true
instanceOptions:
  setMetaProfile: standalone-only


pages:
  index.md:
    title: Home
    generation: markdown
  business-analysis.md:
    title: Business Analysis
    generation: markdown
  LTW.md:
    title: Laboratory Testing Workflow (LTW)
    generation: markdown
  PAM.md:
    title: Patient Administration (PAM)
    generation: markdown
  HPD.md:
    title: Healthcare Provider Directory (HPD)
    generation: markdown
  HIE.md:
    title: Health Information Exchange (HIE)
    generation: markdown
  LAB-1.md:
    title: Placer Order Management [LAB-1]
    generation: markdown
  LAB-2.md:
    title: Filler Order Management [LAB-2]
    generation: markdown
  LAB-3.md:
    title: Order Results Management [LAB-3]
    generation: markdown
  LAB-4.md:
    title: Work Order Management [LAB-4]
    generation: markdown
  LAB-5.md:
    title: Test Results Management [LAB-5]
    generation: markdown
  QEDm.md:
    title: Query Existing Data [QEDm]
    generation: markdown
  MHD.md:
    title: Mobile Access to Health Documents [MHD]
    generation: markdown
  PDQm.md:
    title: Patient Demographics Query for Mobile (PDQm)
    generation: markdown
  DDD-Overview.md:
    title: Overview
    generation: markdown
  hl7v2.md:
    title: HL7 v2 Standards
    generation: markdown
  architecture.md:
    title: Architecture
    generation: markdown
  testing.md:
    title: Testing
    generation: markdown
  support.md:
    title: Support
    generation: markdown
  authorisation.md:
    title: Authorisation (OAuth2)
    generation: markdown
  deployment.md:
    title: Deployment
    generation: markdown
  delivery.md:
    title: Delivery Overview
    generation: markdown
  IUA.md:
    title: OAuth2
    generation: markdown
  workflow-interaction-options.md:
    title: Workflow/Interaction Options
    generation: markdown
  workflow-report-options.md:
    title: Report Options
    generation: markdown
  identifiers.md:
    title: Identifiers and Codes
    generation: markdown
  data-intro.md:
    title: Data Contracts and Issue Reporting
    generation: markdown
  mCSD.md:
    title: Care Services Discovery
    generation: markdown
  SET.md:
    title: Specimen Event Tracking (SET)
    generation: markdown
  ILW.md:
    title: Inter Laboratory Workflow (ILW)
    generation: markdown
  simple.md:
    title: Simple
    generation: markdown
  BPPC.md:
    title: Digital Consent (IHE BPPC and PCF)
    generation: markdown
  design.md:
    title: Design
    generation: markdown

resources:
  Questionnaire/GenomicTestOrder:
    name: North West Genomics Test Order
    description: NHS England North West Genomics Test Order (Draft)
    exampleBoolean: false
  Questionnaire/24323-8:
    name: Comprehensive metabolic 2000 panel - Serum or Plasma
    description: Comprehensive metabolic 2000 panel - Serum or Plasma
    exampleBoolean: false
  Questionnaire/Pedigree:
    name: Pedigree
    description: Initial elaboration of pedigree
    exampleBoolean: false
  Observation/brca1-variant:
    name: Genomic Report BRCA1 Variant Example
    description: Genomic Report BRCA1 Variant Example
    exampleBoolean: true
  Observation/m2-diagnostic-implication:
    name: Genomic Report Ovarian Carcinoma Diagnostic Implication Example
    description: Genomic Report Ovarian Carcinoma Diagnostic Implication Example
    exampleBoolean: true
  Bundle/Bundle-NonWGSTestOrderForm-CancerSolidTumor-Example:
    name: Bundle-NonWGSTestOrderForm-CancerSolidTumor-Example
    description: See [Bundle-NonWGSTestOrderForm-CancerSolidTumor-Example](https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Examples/Bundle#Bundle-NonWGSTestOrderForm-CancerSolidTumor-Example)
    exampleBoolean: true
  Bundle/Bundle-NonWGSTestOrderForm-FetalScenario-Example:
    name: Bundle-NonWGSTestOrderForm-FetalScenario-Example
    description: See [Bundle-NonWGSTestOrderForm-FetalScenario-Example](https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Examples/Bundle#Bundle-NonWGSTestOrderForm-FetalScenario-Example)
    exampleBoolean: true
  Bundle/Bundle-NonWGSTestOrderForm-Reanalysis-Example:
    name: Bundle-Bundle-NonWGSTestOrderForm-Reanalysis-Example
    description: See [Bundle-Bundle-NonWGSTestOrderForm-Reanalysis-Example](https://simplifier.net/guide/fhir-genomics-implementation-guide/Home/Examples/ServiceRequest?version=0.4.3#ServiceRequest-NonWGSTestOrderForm-ReAnalysis-Example-duplicate-2)
    exampleBoolean: true
  NamingSystem/nhs-number-namingsystem:
    name: NHS Number
    exampleBoolean: false
  NamingSystem/ods-organization-code-namingsystem:
    name: ODS Code
    exampleBoolean: false
  NamingSystem/ods-site-code-namingsystem:
    name: ODS Site Code
    exampleBoolean: false
  NamingSystem/gmcnumber-namingsystem:
    name: GMC Number
    exampleBoolean: false
  NamingSystem/gmpnumber-namingsystem:
    name: GMP Number
    exampleBoolean: false
  OperationOutcome/operation-outcome-validate:
    name: Output from a FHIR Validation
    exampleBoolean: true
  DocumentReference/Y05868-d783361d-83fa-438f-977c-601f30ef5ceb:
    name: NRL Genomic Report for Tommen BIRMINGHAM (Test NHS Number 9737383249). Original order not electronic
    description: Proof of concept example. Type, category, custodian and author are currently incorrect values
    exampleBoolean: true
  DocumentReference/Y05868-75c254c0-d2cf-43ee-8a83-926af3f302bb:
    name: NRL Genomic Report for Cersei LONDON (Test NHS Number 9737383230). Original order electronic from EPIC system
    description: Proof of concept example. Type, category, custodian and author are currently incorrect values
    exampleBoolean: true

menu:
  Home: index.html
  Analysis and Design (Volume 1) :
    Design Overview: design.html
    Laboratory Testing Workflow (LTW): LTW.html
    Inter-Laboratory Workflow (ILW): ILW.html
    Specimen Event Tracking (SET): SET.html
    Health Information Exchange (HIE): HIE.html
    Care Services Discovery (mCSD): mCSD.html
    Patient Administration (PAM): PAM.html
    Authorisation (OAuth2): authorisation.html
    Digital Consent (BPPC and PCF): BPPC.html

  Interfaces (Volume 2):
    Placer Order Management [LAB-1] HL7 FHIR: LAB-1.html
##    Filler Order Management [LAB-2]: LAB-2.html
    Order Results Management [LAB-3] HL7 FHIR: LAB-3.html
    Patient Demographics Query for Mobile [PDQm]: PDQm.html
    Query Summary Data [MHD]: MHD.html
    Query Detailed Data [QEDm]: QEDm.html
    Authorisation [IUA] : IUA.html
##    Work Order Management [LAB-4]: LAB-4.html
##    Test Results Management [LAB-5]: LAB-5.html
  Data Models (Volume 3):
    Data Contracts and Issue Reporting: data-intro.html
    Genomic Test Order (Template): Questionnaire-GenomicTestOrder.html
   ## Genomic Test Report (Composition): StructureDefinition-Composition-GenomicReport.html
    Genomic Test Report (Template): Questionnaire-GenomicTestReport.html
  Artefacts (Volume 4):
    HL7 FHIR R4: artifacts.html
    HL7 v2.5.1: hl7v2.html
  Development:
    Environments and Testing: testing.html
    Support: support.html
    Architecture: architecture.html

groups:
  -ex-example-laboratory-order:
    name: "Example: Laboratory Order"
    description: "Laboratory Order Examples"
    resources:
      - Binary/0a898233-763c-405d-8172-8c4f07e6e636
      - Bundle/GenomicsOrderMessageReplyOk
      - Bundle/GenomicsOrderMessageAttachment
      - Bundle/GenomicsOrderMessageCodedEntries
      - Bundle/GenomicsOrderSearchSet
      - DocumentReference/a293b4a6-e46b-4402-9b2b-d9517afc7137
      - Encounter/984b8a89-4194-4eb4-a7ea-ca8049ebeea3
      - MessageHeader/MessageHeaderGenomicOrder
      - MessageHeader/MessageHeaderGenomicOrderReplyOk
      - Patient/Patient-OctaviaCHISLETT-9449305552
      - PractitionerRole/ee9b8fcc-c233-43e1-b7fb-b58ce4cf1db8
      - ServiceRequest/ServiceRequestGenomicsOrderCodedEntries
      - ServiceRequest/ServiceRequestGenomicsOrderAttachment
      - Specimen/SpecimenExample
  -ex-example-laboratory-report:
    name: "Example: Laboratory Report"
    description: "Laboratory Report Examples"
    resources:
      - Binary/d6eeedd1-92d3-45b9-bf33-6401e804425f
      - Bundle/GenomicsReportMessage
      - DiagnosticReport/DiagnosticReportGenomicsReport
      - DocumentReference/94bf65ba-cd6c-4601-b339-6d547f424646
      - MessageHeader/MessageHeaderGenomicReport
  -ex-example-structured-laboratory-report:
    name: "Example: Laboratory Report Structured"
    description: "Laboratory Report Structured Examples"
    resources:
      - Observation/6beb613f-d303-42af-b025-86e8e0872061
      - Observation/8385c2fd-313d-4fd5-b98e-d5ea4bae6f99
      - Procedure/7b362aa5-41a7-4168-94b4-f12dff0dfb2a
      - Procedure/f0036554-cd1a-463c-ac8a-d891ca409af9
      - Observation/bca547c1-78a5-41be-8cfc-03c05805ac85
      - Observation/a954a98c-f427-4968-9022-8b760de66628
  -ex-example-other:
    name: "Example: Ask at Order Entry questions and prior results"
    description: "Ask at Order Entry questions and prior results"
    resources:
      - Bundle/FHIRDocumentGeneticReportBundle
      - Composition/Composition-GenomicsReport-OctaviaCHISLETT
      - Observation/EPIC-OBR-1
      - Observation/OBX-GenomicReferralCategory
      - Observation/OBX-SupervisingClinician
      - Observation/OBX-Pregnancy
      - Observation/OBX-HighInfectionRiskSample
      - Observation/OBX-InformedConsent
      - Observation/EPIC-OBX-4
      - Condition/EPIC-OBX-2
      - Observation/EPIC-OBX-6
      - Observation/EPIC-OBX-7
      - Observation/EPIC-OBX-8
      - Observation/EPIC-OBX-10
      - Observation/EPIC-OBX-11
      - Bundle/748683741
  -ex-example-NHS-Genomics-Medicine-Service:
    name: "Example: NHS England Genomics Order Management Service"
    description: "NHS England Genomics Order Management Service"
    resources:
      - Bundle/Bundle-NonWGSTestOrderForm-CancerSolidTumor-Example
      - Bundle/Bundle-NonWGSTestOrderForm-FetalScenario-Example
      - Bundle/Bundle-NonWGSTestOrderForm-Reanalysis-Example
  -ex-nrl:
    name: "Example: NHS England National Record Locator Service"
    description: "NHS England National Record Locator Service"
    resources:
      - DocumentReference/Y05868-d783361d-83fa-438f-977c-601f30ef5ceb
      - DocumentReference/Y05868-75c254c0-d2cf-43ee-8a83-926af3f302bb
