graph TD


EPR[EPR / Order Placer]

TIE["Trust Integration Engine (TIE)"]

subgraph HIE["Genomic Archiving and Communication System (GACS)"];
    RIE["Regional Orchestration Engine (RIE)"]
    GDR["Genomic Data Repository (GDR)"]
end

subgraph APIM[NHS England API Management];
    PDS["Personnel Demographic Service (PDS)"]
    ODS["Organisation Terminology Service (ODS)"]
end

LIMS[LIMS / Order Filler]

EPR <--> |Document Messaging<br/>HL7 OML| TIE
TIE <--> RIE
RIE <--> |Document Messaging<br/>HL7 ORU| LIMS
RIE --> |"FHIR RESTful API (GET/PUT/POST/DELETE)"| GDR


RIE --> |FHIR RESTful API<br/>Patient Matching| PDS
RIE --> |FHIR RESTful API<br/>Organisation Lookups| ODS


classDef purple fill:#E1D5E7;
classDef pink fill:#F8CECC;


class EPR,TIE,LIMS,DC purple;
class DM,HL7UK pink;
