sequenceDiagram

participant DataConsumer As Document Consumer
participant DocumentRegistry as Document Registry<br/>National Record Locator Service (NRL)
participant DocumentRepository As Document Repository Source<br/>NW Genomics Analysis and Communication System (GACS)


note over DataConsumer,DocumentRegistry: Find Document References<br/>NRL Retrieve patient's document pointers (GET)
DataConsumer ->> DocumentRegistry: GET DocumentReference?patient={id}
DocumentRegistry -->> DataConsumer: search results
alt for each document
note over DataConsumer,DocumentRepository: Retrieve Document
    DataConsumer ->> DocumentRepository: GET /Binary/{id}
    DocumentRepository -->> DataConsumer: PDF Document
end