sequenceDiagram

participant DataConsumer As Data Consumer<br/>NEY Genomics
participant APIGateway As API Gateway<br/>(FHIR Facade)
participant GACS As Data Repository<br/>NW Genomics Analysis and Communication System (GACS)<br/>(FHIR Respository)


note over DataConsumer,GACS: Poll for new or updated orders
DataConsumer ->> APIGateway: GET /$find-test-metadata?_lastUpdated={date}&ICSODSCode={list of ICSODSCode}
APIGateway ->> GACS: Get a list of NHS Trust within ICB region <br>Get /Organisation?partof={ICSCode}&type=R0197
GACS -->> APIGateway: Search results
APIGateway ->> GACS: Get test metadata <br/>GET /ServiceRequest?_lastUpdated={date}&requestor={list of organisation ids}&_revinclude=DiagnosticReport:based-on<br/>&_include=ServiceRequest:specimen&_include=ServiceRequest:patient
GACS -->> APIGateway: search results
APIGateway -->> DataConsumer: RPC `find-test-metadata` results
