sequenceDiagram

participant DataConsumer As Data Consumer<br/>NEY Genomics
participant APIGateway As API Gateway<br/>(FHIR Facade)
participant GACS As Data Repository<br/>NW Genomics Analysis and Communication System (GACS)<br/>(RIE + GDR)
participant LIMS as LIMS iGene<br/>(NW Genomics)

note over LIMS,GACS: This is equivalent to a HL7 v2 O21 Event Message
GACS ->> LIMS: Synchronise Data with iGene SQL Database (copy)
GACS ->> GACS: Update GDR

note over DataConsumer,GACS: Poll for new or updated orders
DataConsumer ->> APIGateway: GET /$find-test-metadata?_lastUpdated={date}&ICSODSCode={list of ICSODSCode}
APIGateway ->> GACS: Get a list of NHS Trust within ICB region <br>Get /Organisation?partof={ICSCode}&type=R0197
GACS -->> APIGateway: Search results
APIGateway ->> GACS: Get test metadata <br/>GET /ServiceRequest?_lastUpdated={date}&requestor={list of organisation ids}&_revinclude=DiagnosticReport:based-on<br/>&_include=ServiceRequest:specimen&_include=ServiceRequest:patient
GACS -->> APIGateway: search results
APIGateway -->> DataConsumer: RPC `find-test-metadata` results
