graph LR



subgraph Analysis[Data Analysis];

    LIMS["LIMS iGene"]

end


subgraph RIE["Genomic Archiving and Communication System (GACS)"];

    Report["Regional Orchestration Engine (RIE)"]
    FHIRLIMS@{ shape: docs, label: "Patient, ServiceRequest, DiagnosticReport, Observation, DocumentReference and Specimen"}

    GDR@{ shape: cyl, label: "Genomic Data Repository<br/>(FHIR Server)"}
end



EPR@{ shape: cyl, label: "NHS Trust EHR"}


LIMS --> |HL7 v2 ORU_R01 Report| Report
Report --> |HL7 O21 Order| LIMS
Report --> |PDF + Metadata<br/>HL7 v2 ORU_R01| EPR
EPR --> |HL7 O21 Order| Report
Report --> FHIRLIMS
FHIRLIMS --> GDR



classDef purple fill:#E1D5E7;
classDef pink fill:#F8CECC;

class EPR,TIE,LIMS,DC,Registry purple;

class GDR,FHIRLIMS pink;
