graph

RespiratoryService

subgraph InitialAssessmentAndImaging;
    Radiology
    RadiologyReport@{ shape: docs, label: "Radiology Report includes:<br/>ServiceRequest<br/>DiagnosticReport<br/>Specimen<br/>Images"}
end

RespiratoryService --> |1a. Referral| Radiology
Radiology --> |1b. Images and Report| RadiologyReport
RadiologyReport --> RespiratoryService

subgraph TissueSamplingBiopsyAndProcedures;
   Biopsies
end

RespiratoryService --> |2a. Referral| Biopsies

subgraph LaboratoryAnd MolecularTesting;

Pathology

Genomics

GenomicReport@{ shape: docs, label: "Genomic Report includes:<br/>ServiceRequest<br/>DiagnosticReport<br/>Specimen<br/>PDF Report<br/>Observations - Molecular/BioMarkers"}
PathologyReport@{ shape: docs, label: "Pathology Report includes:<br/>ServiceRequest<br/>DiagnosticReport<br/>Specimen<br/>Observations - Tissue Histology"}
end

Biopsies --> |2b. Send Sample| Pathology
Pathology --> |2c. Referral and Send Liquid Biopsy Sample| Genomics

Genomics --> GenomicReport
GenomicReport --> RespiratoryService

Pathology --> PathologyReport
PathologyReport --> RespiratoryService

LungCancerMDT[Lung Cancer MDT<br/>Likely to be supported by several NHS England programmes]

RadiologyReport --> LungCancerMDT
PathologyReport --> LungCancerMDT
GenomicReport --> LungCancerMDT

classDef purple fill:#E1D5E7;
classDef pink fill:#F8CECC;

class Genomics,GenomicReport pink