graph LR


subgraph Analysis[Reporting];

    Assessment@{ shape: docs, label: "Genomic Assessment"}
    LIMS["LIMS iGene"]
    Assessment --> LIMS

end


subgraph GACS["Genomic Archiving and Communication System (GACS)"];

      RIE["Regional Orchestration Engine (RIE)"]
    FHIRLIMS@{ shape: docs, label: "Patient, ServiceRequest, DiagnosticReport, DocumentReference and Specimen"}

    GDR@{ shape: cyl, label: "Genomic Data Repository<br/>(FHIR Server)"}
    API["API Gateway<br/>(FHIR Facade)"]
end

DC["Data Consumer"]


LIMS --> |HL7 v2 ORU_R01| RIE

RIE --> FHIRLIMS
FHIRLIMS --> GDR

DC --> |Genomic Data<br/>FHIR RESTful + Resource| API
API --> |Genomic Data<br/>FHIR RESTful + Resource| GDR


classDef purple fill:#E1D5E7;
classDef pink fill:#F8CECC;

class EPR,TIE,LIMS,DC,Registry purple;

class GDR,FHIRLIMS,API pink;
