graph LR



subgraph Analysis[Reporting];

    LIMS["LIMS iGene"]

end


subgraph GACS["Genomic Archiving and Communication System (GACS)"];

    RIE["Regional Orchestration Engine (RIE)"]
    FHIRLIMS@{ shape: docs, label: "Patient, ServiceRequest, DiagnosticReport, Observation, DocumentReference and Specimen"}

    GDR@{ shape: cyl, label: "Genomic Data Repository<br/>(FHIR Repository)"}
end

subgraph APIM[NHS England API Management];
    PDS["Personnel Demographic Service (PDS)"]
    ODS["Organisation Terminology Service (ODS)"]
end


EPR@{ shape: cyl, label: "GMCR and Share2Care"}

LIMS --> |HL7 v2 ORU_R01 Report| RIE

RIE --> |PDF + Metadata<br/>HL7 v2 ORU_R01| EPR
RIE --> FHIRLIMS
FHIRLIMS --> GDR
RIE --> |FHIR RESTful API<br/>Patient Matching| PDS
RIE --> |FHIR RESTful API<br/>Organisation Lookups| ODS


classDef purple fill:#E1D5E7;
classDef pink fill:#F8CECC;

class EPR,TIE,LIMS,DC purple;

class GDR,FHIRLIMS pink
