graph TD

DC["Document Consumer (PDF)"]

Registry[Document Registry<br/>National Record Locator]
Repository[Document Repository<br/>]

subgraph RIE["NW Genomic Archiving and Communication System (GACS)"];

    GDR@{ shape: cyl, label: "Genomic Data Repository<br/>(FHIR Repository)"}
    Agg@{ shape: docs, label: "Aggregation Layer<br/>Final Report"}
    DocumentNotificationService

    API["API Gateway<br/>(FHIR Facade)"]
    API --> Agg
    Agg --> |Genomic Data<br/>FHIR RESTful + Resource| GDR
end

DC --> |Find Document References| Registry
DC --> |Retrieve Document| Repository

DocumentNotificationService --> |POST FHIR DocumentReference| Registry

Repository --> API

classDef purple fill:#E1D5E7;
classDef pink fill:#F8CECC;

class EPR,TIE,LIMS,DC,Registry,Repository purple;
class DM,HL7UK pink;