graph LR

subgraph Gen ["Data Generation"];

    Data@{ shape: docs, label: "Raw Data:<br/>VCF Data Files<br/>Metadata"}

end

subgraph Analysis[Data Analysis];

    Assessment@{ shape: docs, label: "Genomic Assessment"}

    LIMS["LIMS iGene"]


    Assessment --> LIMS

end


subgraph RIE[Orchestration and Data Platform];

    Report@{ shape: docs, label: "Final Report"}
    FHIRLIMS@{ shape: docs, label: "Patient, ServiceRequest, DiagnosticReport, DocumentReference and Specimen"}

    GDR@{ shape: cyl, label: "Genomic Data Repository<br/>(FHIR Server)"}
    API["API Gateway<br/>(FHIR Facade)"]
end

DC["Data Consumer"]

Data --> Analysis


EPR@{ shape: cyl, label: "NHS Trust EHR & ICS"}


LIMS --> |HL7 v2 ORU_R01| Report
Report --> |PDF + Metadata<br/>HL7 v2 ORU_R01 or MDM_T02| EPR
Report --> FHIRLIMS
FHIRLIMS --> GDR

DC --> |Genomic Data<br/>FHIR RESTful + Resource| API
API --> |Genomic Data<br/>FHIR RESTful + Resource| GDR


classDef purple fill:#E1D5E7;
classDef pink fill:#F8CECC;

class EPR,TIE,LIMS,DC,Registry purple;

class GDR,FHIRLIMS,API pink;
