CodeSystem: GenomicTestOutcomeCode
Id: GenomicTestOutcomeCode
Title: "NHS England Genomic Test Outcome Code"
Description: """
Test Outcome Code from [NHS England Genomics Test Reporting Specification](https://www.england.nhs.uk/publication/genomics-testing-reporting-specification/)
"""

* ^name = "GenomicTestOutcomeCode"
* ^content = #complete
* ^caseSensitive = true
* ^experimental = false
* ^status = #draft
* ^version = "0.0.1"
* ^date = "2025-05-08"
* ^url = "https://fhir.nwgenomics.nhs.uk/CodeSystem/GenomicTestOutcomeCode"

* #311 "RESULT CONSISTENT WITH REFERRAL INDICATION"
* #312 "RESULT  PARTIALLY CAUSATIVE OF REFERRAL INDICATION"
* #313 "GENETIC CAUSE WAS NOT FOUND"
* #314 "RESULT OF UNCERTAIN SIGNIFICANCE"
* #321 "VARIANT DETECTED"
* #322 "VARIANT NOT DETECTED"
* #323 "FAMILY MEMBER TESTED TO AID INTERPRETATION OF PROBAND’S TEST; NOT INDEPENDENTLY ANALYSED"
* #331 "VARIANT(S) DETECTED"
* #332 "VARIANT(S) NOT DETECTED"
* #411 "ONCOGENIC/LIKELY ONCOGENIC VARIANT DETECTED CONTRIBUTING TO THE SUSPECTED DIAGNOSIS"
* #412 "ONCOGENIC/LIKELY ONCOGENIC VARIANT DETECTED WHICH CONTRIBUTES TO AN ALTERNATIVE DIAGNOSIS"
* #413 "NO ONCOGENIC/LIKELY ONCOGENIC VARIANT DETECTED WHICH REDUCES LIKELIHOOD BUT DOES NOT EXCLUDE (DIFFERENTIAL) DIAGNOSIS/DIAGNOSES"
* #421 "VARIANT DETECTED – WHERE A TARGETED TREATMENT IS AVAILABLE OR WHERE PROGNOSTIC/ACTIONABLE INFORMATION IS PROVIDED"
* #422 "WILDTYPE RESULT OBTAINED – WHERE THE ABSENCE OF A VARIANT MEANS TARGETED TREATMENT IS NOT AVAILABLE"
* #423 "WILDTYPE RESULT OBTAINED – WHERE THE ABSENCE OF A VARIANT MEANS TARGETED TREATMENT IS AVAILABLE OR WHERE PROGNOSTIC/ACTIONABLE INFORMATION IS PROVIDED"
* #431 "TARGET DETECTED AT A LEVEL REQUIRING CLINICAL ACTION"
* #432 "NO TARGET DETECTED OR TARGET DETECTED BELOW A LEVEL REQUIRING CLINICAL ACTION"
* #961 "ACTIONABLE PHARMACOGENOMIC VARIANT DETECTED"
* #962 "NO ACTIONABLE PHARMACOGENOMIC VARIANT DETECTED"
* #971 "FAILURE"
* #981 "ONCOGENIC/LIKELY ONCOGENIC VARIANT DETECTED IN GENE NOT ASSOCIATED WITH TUMOUR TYPE/INCIDENTAL FINDING"
* #991 "OTHER (NOT LISTED)"
* #992 "CAVEATED RESULT"


